### ISSUE TITLE
You opened a ticket with your benchmark. I did measured on my side. results are different ...

### ISSUE THREAD

**Issue by unix-world** [teal-finance/BaseXX#1]
### I have did my own benchmark and my results are completely different than yours smartgo basexx is a bit faster than yours ...
https://github.com/unix-world/smartgo/issues/1

**Comment by 0uep** [comment]
Dear Radu @unix-world 

I have implemented a bench you can execute on your side: https://github.com/teal-finance/BaseXX/blob/main/examples/bench/main.go

For simplicity, this bench measures together the encoding and decoding durations:

```go
start := time.Now()
str := s92.Encode(bin)
_, _ = s92.Decode(str)
d := time.Since(start)
```

I do not think necessary to split it in two measures. But, I may be wrong… Please give me your feedback.

Please run the bench on your side as the following:

```
$ go run github.com/teal-finance/BaseXX/examples/bench@latest -f gpl-3.0.txt
2022/05/20 14:38:02 File: gpl-3.0.txt	Size: 34 KB
2022/05/20 14:38:02 Number of loops: 28
2022/05/20 14:40:04  mtraver/base91    284 us   8%
2022/05/20 14:40:04   BaseXX/base91     1.6 s   1%
2022/05/20 14:40:04   BaseXX/base92     1.3 s   1%
2022/05/20 14:40:04  smartgo/base92     1.4 s   1%
```

That above execution takes about 2 minutes on my computer.

My conclusion: our both Base92 implementations have similar performance.

----------------------
NB: For your information, I do not currently use my BaseXX/Base92, I have switched to https://github.com/mtraver/base91 (see the [incorruptible](https://github.com/teal-finance/incorruptible/blob/main/incorruptible.go#L17) project)
